#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 21 14:48:04 2019

@author: jacobarnold

This will be my first view of the data from TABS 225 in the eastern Mediterranean
2017/07/26 TO 2019/01/21

"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


#%%
The_ADCP = pd.read_csv('Documents/Classes/THEMO/TABS225m09/Data/adcp.csv',
                   parse_dates=[[0,1]], infer_datetime_format = True, index_col=0)
The_ADCP.rename(columns = {'depth[m]':'depth', 'direction[deg]':'direction','speed[m/s]':'speed'}, inplace=True)
#Acoustic Doppler Current Profiler Depth, Direction in degrees, Speed in m/s

#%%

surf_cur = pd.read_csv('Documents/Classes/THEMO/TABS225m09/Data/dcs.csv',
                       parse_dates=[[0,1]], infer_datetime_format = True, index_col=0)
#Near surface current velocity (m/s)

fluor = pd.read_csv('Documents/Classes/THEMO/TABS225m09/Data/flntu.csv',
                    parse_dates=[[0,1]], infer_datetime_format = True, index_col=0)
#Fluorescence recorded at 1m (Chlorophyll in μg/L) (Turbidity in NTU)

salinity = pd.read_csv('Documents/Classes/THEMO/TABS225m09/Data/microcat.csv',
                       parse_dates=[[0,1]], infer_datetime_format = True, index_col=0)
#Salinity (PSU), conductivity(S/m), and temperature(degrees celcius) recorded at 1m 

temp_prof = pd.read_csv('Documents/Classes/THEMO/TABS225m09/Data/s9.csv', 
                        parse_dates=[[0,1]], infer_datetime_format = True, index_col=0)
#Temperature recorded at different depths beginning at 5m and ending at 85m (degrees celcius)

met_pak = pd.read_csv('Documents/Classes/THEMO/TABS225m09/Data/metpak.csv',
                       parse_dates=[[0,1]], infer_datetime_format = True, index_col=0)
#Meteorology package - Air temp (degrees Celcius), Relative humidity (%), Wind Velocity (m/s) and pressure (millibars).

wind_vel = pd.read_csv('Documents/Classes/THEMO/TABS225m09/Data/windsonic.csv',
                       parse_dates=[[0,1]], infer_datetime_format = True, index_col=0)
#Wind velocity recorded at -3m (meters/second)

humid = pd.read_csv('Documents/Classes/THEMO/TABS225m09/Data/mp101a_humidity.csv',
                    parse_dates=[[0,1]], infer_datetime_format = True, index_col=0)
#Humidity in the air recorded at -3m (RH%)

temp_air = pd.read_csv('Documents/Classes/THEMO/TABS225m09/Data/mp101a_temprature.csv',
                       parse_dates=[[0,1]], infer_datetime_format = True, index_col=0)
#Temperature of the air recorded at -3m (degrees celcius)

baro = pd.read_csv('Documents/Classes/THEMO/TABS225m09/Data/barometer.csv',
                   parse_dates=[[0,1]], infer_datetime_format = True, index_col=0)
#Barometric pressure recorded at -3m (millibar)

waves = pd.read_csv('Documents/Classes/THEMO/TABS225m09/Data/waves.csv',
                    parse_dates=[[0,1]], infer_datetime_format = True, index_col=0)
#Height of waves (meters) period of waves (seconds)


#%%
#plt.style.use('ggplot')
#plt.style.use('classic')
#plt.style.use('dark_background')

#%%
'''clean salinity'''
salinity.Salinity[salinity.Salinity < 20] = np.nan
salinity.Conductivity[salinity.Conductivity < 3] = np.nan

#%%
'''clean waves domimant period'''
waves.dominant_period[waves.dominant_period > 30]

#%%
'''Salinity Plot'''
s9plot = salinity.Salinity.plot.line(figsize=(15,3), legend=False)
s9plot.set_title('TABS225 CalSpike-Filtered Salinity')
s9plot.set_xlabel('Date')
s9plot.set_ylabel('Salinity')
fig = s9plot.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/salinity_calspike_filtered.png',bbox_inches='tight',dpi=400)

#%%
'''Temp from s9 Plot'''
s9plotT = salinity.Temperature.plot.line(figsize=(15,3), legend=False)
s9plotT.set_title('TABS225 Unfiltered s9 Temperature')
s9plotT.set_xlabel('Date')
s9plotT.set_ylabel('Temperature ($\circ$C)')
fig = s9plotT.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/temp_from_s9_unfiltered.png',bbox_inches='tight',dpi=400)

#%%
'''Waves Height Plot'''
wavesplot = waves.significant_height.plot.line(figsize=(15,3), legend=False)
wavesplot.set_xlabel('Date')
wavesplot.set_ylabel('Wave Height (m)')
wavesplot.set_title('TABS225 Unfiltered Waves Significant Height')
fig = wavesplot.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/waves_height_unfiltered.png',bbox_inches='tight',dpi=400)

#%%
'''Waves Mean Period Plot'''
wavesplot = waves.mean_period.plot.line(figsize=(15,3), legend=False)
wavesplot.set_xlabel('Date')
wavesplot.set_ylabel('Period (s)')
wavesplot.set_title('TABS225 Unfiltered Waves Mean Period')
fig = wavesplot.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/waves_Mperiod_unfiltered.png',bbox_inches='tight',dpi=400)

#%%
'''Waves Dominant Period Plot'''
wavesplot = waves.dominant_period.plot.line(figsize=(15,3), legend=False)
wavesplot.set_xlabel('Date')
wavesplot.set_ylabel('Period (s)')
wavesplot.set_title('TABS225 Unfiltered Waves Dominant Period')
fig = wavesplot.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/waves_Dperiod_unfiltered.png',bbox_inches='tight',dpi=400)


#%%
'''Flourometer Plot'''
flourometer = flour.plot.line(figsize=(15,3))
flourometer.set_title('TABS225 Unfiltered Flourometer')
flourometer.set_xlabel('Date')
fig = flourometer.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/ALL_raw_flourometer.png',bbox_inches='tight',dpi=400)

#%%
'''Temperature Profile Timeseries Plot'''
ptemp = temp_prof.temperature.plot.line(figsize=(15,3), legend=True)
ptemp.set_title('TABS225 Unfiltered Temperature Profiler')
ptemp.set_xlabel('Date')
ptemp.set_ylabel('Temperature ($\circ$C)')
ptemp = temp_prof.depth.plot.line(secondary_y=True, figsize=(12,3), alpha=.2, legend=True)
ptemp.set_ylabel('Depth')
fig = ptemp.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/raw_temp_profiler.png',bbox_inches='tight',dpi=400)


#%%
'''Air Temperature Plot'''
air_temp = temp_air['AvgLinearAdjVal'].plot.line(figsize=(15,3), )
air_temp.set_title('TABS225 Unfiltered Air Temperature')
air_temp.set_xlabel('Date')
air_temp.set_ylabel('Degrees ($\circ$C)')
fig = air_temp.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/raw_temp_air.png',bbox_inches='tight',dpi=400)
#%%
'''Air Pressure Plot'''
air_pressure = baro['BAROMETER'].plot.line(figsize=(15,3))
air_pressure.set_title('TABS225 Unfiltered Air Pressure')
air_pressure.set_xlabel('Date')
air_pressure.set_ylabel('Pressure (mbar)')
fig = air_pressure.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/ALL_raw_pressure.png',bbox_inches='tight',dpi=400)

#%%
'''Wind Velocity'''
wv = wind_vel.north.plot.line(figsize=(15,3), legend=True)
wv = wind_vel.east.plot.line(figsize=(15,3), legend=True)
wv.set_ylabel('Velocity (m/s)')
wv = wind_vel.winddirection.plot.line(figsize=(15,3), secondary_y=True, alpha=.2, legend=True)
wv.set_ylabel('Wind Direction ($\circ$)')
wv.set_title('TABS225 Unfiltered Wind Velocity')
wv.set_xlabel('Date')
fig = wv.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/raw_windV.png',bbox_inches='tight',dpi=400)


#%%
'''Humidity Plot'''
humid = humid['AvgLinearAdjVal'].plot.line(figsize=(15,3))
humid.set_title('TABS225 Unfiltered Humidity')
humid.set_xlabel('Date')
humid.set_ylabel('Relative Humidity (%)')
fig = humid.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/humidity_unfiltered.png',bbox_inches='tight',dpi=400)


#%%
'''ADCP Plot'''
ADCP = The_ADCP.plot.line(figsize=(15,3), legend=True)
ADCP.set_title('TABS225 ADCP Time Series')
ADCP.set_xlabel('Date')
fig = ADCP.get_figure()
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/salinity_calspike_filtered.png',bbox_inches='tight',dpi=400)









#%%
'''Scatter plot of salinity'''
plt.figure(figsize = (15,3))
plt.scatter(x = salinity.index, y = 'Salinity', data = salinity, s=1.5)
plt.title('Salinity <20 Filtered')
plt.xlabel('Date')
plt.ylabel('Salinity')
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/scat_salinity_less20_filtered.png',bbox_inches='tight',dpi=400)

#%%
'''Scatter plot of temp from s9'''
plt.figure(figsize = (15,3))
plt.scatter(x = salinity.index, y = 'Temperature', data = salinity, s=1.5)
plt.title('TABS225 Unfiltered Surfact Temperature from Salinity Device')
plt.xlabel('Date')
plt.ylabel('Temperature ($\circ$C)')
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/scat_temp_froms9_unfiltered.png',bbox_inches='tight',dpi=400)

#%%
'''Scatter plot of waves height'''
plt.figure(figsize = (15,3))
plt.scatter(x = waves.index, y = 'significant_height', data = waves, s=1.5)
plt.title('TABS225 Unfiltered Waves Significant Height')
plt.xlabel('Date')
plt.ylabel('Wave Height (m)')
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/scat_waves_sight_unfiltered.png',bbox_inches='tight',dpi=400)

#%%
'''Scatter plot of waves mean period'''
plt.figure(figsize = (15,3))
plt.scatter(x = waves.index, y = 'mean_period', data = waves, s=1.5)
plt.title('TABS225 Unfiltered Waves Mean Period')
plt.xlabel('Date')
plt.ylabel('Wave Period (s)')
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/scat_waves_mean_period_unfiltered.png',bbox_inches='tight',dpi=400)

#%%
'''Scatter plot of waves dominant period'''
plt.figure(figsize = (15,3))
plt.scatter(x = waves.index, y = 'dominant_period', data = waves, s=1.5)
plt.title('TABS225 Unfiltered Waves Dominant Period')
plt.xlabel('Date')
plt.ylabel('Wave Period (s)')
#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/scat_waves_dom_period_unfiltered.png',bbox_inches='tight',dpi=400)

#%%
'''Scatter plot of flourometer'''
plt.figure(figsize = (15,3))
plt.scatter(x = flour.index, y ='chlorophyll_concentration', data = flour, s=1.5)
plt.scatter(x = flour.index, y ='turbidity_units', data = flour, s=1.5)
plt.title('TABS225 Unfiltered Flourometer')
plt.legend()
plt.xlabel('Date')

#fig.savefig('Documents/Classes/OCNG491/THEMO/ABC_17_07_26-19_01_21/Time_series/blue_white/scat_waves_mean_period_unfiltered.png',bbox_inches='tight',dpi=400)


#%%
'''Scatter plot of temperature profiler'''
fig, ax1 = plt.subplots(figsize = (15,3))
ax1.scatter(x = temp_prof.index, y = 'temperature', data = temp_prof, s=5)
ax1.set_xlabel('Date')
ax1.set_ylabel('Temperature ($\circ$C)')

ax2 = ax1.twinx()
ax2.scatter(x = temp_prof.index, y = 'depth', data = temp_prof, s=1.5, c = 'green', alpha = .1)
ax2.set_ylabel('Depth (m)')

plt.tight_layout()
plt.show()





